freebsd_instance:
  image: freebsd-12-0-release-amd64

build_task:
  env:
    CIRRUS_WORKING_DIR: /root/go/src/github.com/prometheus/node_exporter
  install_script:
    pkg install -y lang/go devel/git gmake bash;
    go env;
    go env | sh;
    go get github.com/prometheus/node_exporter;
    cd /root/go/src/github.com/prometheus/node_exporter;
    gmake

