freebsd_instance:
  image: freebsd-12-0-release-amd64

build_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME
  install_script: pkg install -y lang/go devel/git && go get github.com/prometheus/node_exporter && cd ${GOPATH-$HOME/go}/src/github.com/prometheus/node_exporter && make

